/**
 * scripts/set-env.js
 *
 * Reads .env from the project root and writes Angular environment files:
 *   src/environments/environment.ts      (development)
 *   src/environments/environment.prod.ts (production)
 *
 * Run manually:   node scripts/set-env.js
 * Auto-runs via:  npm start / npm run build  (prestart / prebuild hooks)
 *
 * Copy .env.example → .env and fill in your values before running.
 */

const fs   = require('fs');
const path = require('path');

// ── Parse .env ──────────────────────────────────────────────────────────────
function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠  No .env file found at ${filePath} — using empty/default values.`);
    console.warn('   Copy .env.example → .env and fill in your keys.\n');
    return {};
  }
  return fs.readFileSync(filePath, 'utf-8')
    .split('\n')
    .filter(line => line.trim() && !line.startsWith('#'))
    .reduce((acc, line) => {
      const eqIdx = line.indexOf('=');
      if (eqIdx < 1) return acc;
      const key = line.slice(0, eqIdx).trim();
      const val = line.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
      acc[key] = val;
      return acc;
    }, {});
}

const envPath = path.join(__dirname, '../.env');
const env     = parseEnvFile(envPath);

// Prefer .env value, then process.env (CI secrets), then fallback
const get = (key, fallback = '') =>
  (env[key] !== undefined ? env[key] : (process.env[key] || fallback));

// ── Template ─────────────────────────────────────────────────────────────────
function buildEnvironmentFile(production) {
  return `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/set-env.js — DO NOT EDIT MANUALLY.
// Source: .env  (run \`node scripts/set-env.js\` after changing .env)
// ─────────────────────────────────────────────────────────────────────────────

let environment = {
  production: ${production},

  // ── Firebase ──────────────────────────────────────────────────────────────
  firebaseConfig: {
    apiKey:            '${get('FIREBASE_API_KEY')}',
    authDomain:        '${get('FIREBASE_AUTH_DOMAIN',        'emmanuelkorircv.firebaseapp.com')}',
    databaseURL:       '${get('FIREBASE_DATABASE_URL',       'https://emmanuelkorircv-default-rtdb.firebaseio.com')}',
    projectId:         '${get('FIREBASE_PROJECT_ID',         'emmanuelkorircv')}',
    storageBucket:     '${get('FIREBASE_STORAGE_BUCKET',     'emmanuelkorircv.appspot.com')}',
    messagingSenderId: '${get('FIREBASE_MESSAGING_SENDER_ID','676940554194')}',
    appId:             '${get('FIREBASE_APP_ID',             '1:676940554194:web:bca93d11d7d700ccffb20b')}',
    measurementId:     '${get('FIREBASE_MEASUREMENT_ID',     'G-S5609XRE46')}'
  },

  // ── AI provider keys (used as defaults for Kori; user can override in UI) ─
  openrouterKey: '${get('OPENROUTER_API_KEY')}',
  openaiKey:     '${get('OPENAI_API_KEY')}',
  claudeKey:     '${get('CLAUDE_API_KEY')}',

  // ── App ───────────────────────────────────────────────────────────────────
  baseUrl: '',
  author:  'Emmanuel1017'
};

environment.baseUrl = environment.production
  ? 'https://emmanuel1017.github.io/Angular-Resume'
  : 'http://localhost:4200';

export { environment };
`;
}

// ── Write files ──────────────────────────────────────────────────────────────
const envDir = path.join(__dirname, '../src/environments');

fs.writeFileSync(path.join(envDir, 'environment.ts'),      buildEnvironmentFile(false));
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), buildEnvironmentFile(true));

console.log('✅  src/environments/environment.ts      generated');
console.log('✅  src/environments/environment.prod.ts generated');
